//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCleanB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public string MaPhieuNhap { get; set; }
        public Nullable<int> DonGiaNhap { get; set; }
        public string SoLuongNhap { get; set; }
        public string MaThietBi { get; set; }
        public string id { get; set; }
    }
}
