//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiBosch.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string MaPhieuNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNhanVien { get; set; }
        public string SoLuong { get; set; }
        public string DonGia { get; set; }
        public string MaThietBi { get; set; }
        public string TenThietBi { get; set; }
        public string DonViTinh { get; set; }
    }
}
